spring:
  kafka:
    listener:
      ack-mode: manual
    consumer:
      bootstrapServers: localhost:9093, localhost:9092
      groupId: group_id
      autoOffsetReset: latest
      keyDeserializer: org.apache.kafka.common.serialization.StringDeserializer
      valueDeserializer: org.apache.kafka.common.serialization.StringDeserializer
      pollingDuration: 100
    producer:
      bootstrap-servers: localhost:9093, localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always