spring:
  kafka:
    consumer:
      bootstrapServers: localhost:29092, localhost:39092
      groupId: group_id
      autoOffsetReset: latest
      keyDeserializer: org.apache.kafka.common.serialization.StringDeserializer
      valueDeserializer: org.apache.kafka.common.serialization.StringDeserializer
      maxPollRecords: 5
      pollingDuration: 100
    producer:
      bootstrap-servers: localhost:29092, localhost:39092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    bootstrap-servers: localhost:29092
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

ratelimiter:
  limitForPeriod: 5
  limitRefreshPeriod: 10000
  timeoutDuration: 0
  registerHealthIndicator: true
  eventConsumerBufferSize: 100

postmanEchoApi:
  timeout:
    connect: 2000
    read: 25000
  baseUrl: https://postman-echo.com